modLoader="javafml" #mandatory

loaderVersion="[25,)" #mandatory (24 is current forge version)

[[mods]] #mandatory

modId="torchoptimizer" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Torch Optimizer" #mandatory

credits="Thanks to 4poc for his original version. Thanks to Oldjunyi for continuing it for a time." #optional

authors="kreezxil, Eleksploded" #optional

description='''
Allows you to visualize the intensity of light rendered as numbers on the top of blocks. Optionally display optimal placement of torches.
'''